name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.5'
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake test

    - name: Run StandardRB linter
      run: bundle exec rake lint

    - name: Dump GraphQL schema
      run: bundle exec rake schema:dump

    - name: Verify schema.graphql was generated
      run: test -f schema.graphql

    - name: Generate GraphQL documentation
      run: bundle exec rake docs

    - name: Verify docs were generated
      run: test -f docs/index.html

    - name: Upload schema artifact
      uses: actions/upload-artifact@v4
      with:
        name: graphql-schema
        path: schema.graphql

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: graphql-docs
        path: docs/
